spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  web:
    resources:
      static-locations: file:D:/shipinshu_data/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shipinshu?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath:data_v1.sql
      mode: always

storage:
  path: D:/shipinshu_data